main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Content
    url: /content/
    weight: 3
  - name: Lessons
    url: /lesson/
    weight: 4
  - name: Examples
    url: /example/
    weight: 5
  - name: Assignments
    url: /assignment/
    weight: 6
  - name: Resources
    url: /resource/
    weight: 7
  - name: '<i class="fab fa-slack"></i>'
    url: "https://gsudatavizm2020.slack.com"
    weight: 8
  - name: '<i class="fab fa-r-project"></i>'
    url: "https://rstudio.cloud/"
    weight: 9

content:
  - name: Overview
    weight: 1
  - name: Course content
    weight: 2
lesson:
  - name: Overview
    weight: 1
  - name: Lessons
    weight: 2
example:
  - name: Overview
    weight: 1
  - name: Examples
    weight: 2
assignment:
  - name: Overview
    weight: 1
  - name: Projects
    weight: 2
  - name: Exercises
    weight: 3
resource:
  - name: Resources
    weight: 1
  - name: Guides
    weight: 2
