# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

############################
## Theme
############################

# Choose a theme.
#   Latest themes (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in themes in `themes/academic/data/themes/`
#   Browse user installed themes in `data/themes/`
theme: "plasma"

# Enable users to switch between day and night mode?
day_night: false

# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font: "fira"

# Choose a font size.
# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size: "L"


############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type: "Course"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description: "Communicate science and statistics with beautiful graphics made with R and ggplot2"

# Display a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo: ""


############################
## Site Features
############################

# Enable source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight: true

# Add support for highlighting additional languages
highlight_languages: 
  - r

# highlight_style: "github-gist"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable LaTeX math rendering? true/false
#   If false, you can enable math on a per page basis as needed.
math: true

# Enable diagram rendering? true/false
#   If false, you can enable diagrams on a per page basis as needed.
diagram: false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack: false

# Enable visitors to edit pages?
#   `repo` defines the repository URL. `editable` defines which page types can be edited.
edit_page:
  repo_url: 'https://github.com/andrewheiss/datavizm20.classes.andrewheiss.com'
  content_dir: ''
  repo_branch: master
  editable:
    docs: true
    page: false
    post: false

############################
## Contact details
##
## These details power the Contact widget (if enabled).
## Additionally, for organizations, these details may be used to enrich search engine results.
############################

author: Andrew Heiss

instructor: 
  name: Dr. Andrew Heiss
  email: aheiss@gsu.edu
  url: "https://www.andrewheiss.com"
  twitter: andrewheiss
  github: andrewheiss
  office: "357 Andrew Young School"
  contact_policy: >-
    E-mail and Slack are the best ways to get in contact with me. I will try to respond to all course-related e-mails and Slack messages within 24 hours (*really*), but also remember that life can be busy and chaotic for everyone (including me!), so if I don't respond right away, don't worry!
  appointment_url: https://calendly.com/andrewheiss/meeting/

course:
  number: "PMAP 8921"
  semester: "Maymester 2020"
  days: "Every day"
  time: "Whenever"
  # location: "Online only (thanks, COVID-19, for ruining everything)"
  dates: "May 11â€“June 1, 2020"
  github: "andrewheiss/datavizm20.classes.andrewheiss.com"
  copyrightYear: "2020"
  slack: "https://gsudatavizm2020.slack.com"

university: 
  name: Georgia State University
  url: "https://www.gsu.edu"

school:
  name: Andrew Young School of Policy Studies
  url: "https://aysps.gsu.edu/"


############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image: "social-image.png"

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter: "andrewheiss"


############################
## Regional Settings
############################

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format: "January 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format: "3:04 PM"


############################
## Advanced
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar: false

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu:
  align: r
  show_logo: true

# Show estimated reading time for posts? (true/false)
reading_time: false

# Display next/previous section pager? (true/false)
section_pager: false
docs_section_pager: false  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing: false

# Link authors to their profile page? (true/false)
link_authors: false

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js: ["custom"]`.
plugins_js: []


############################
## Comments
############################

comments:
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  engine: 0

  # Which page types are commentable?
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true

  # Configuration of Disqus.
  disqus:
    shortname: ''  # Paste the shortname from your Disqus dashboard
    show_count: true  # Show comment count in page header? (true/false)

  # Configuration of Commento.
  commento:
    # If self-hosting Commento, enter its URL here (e.g. "https://commento.?.com"), otherwise leave empty.
    url: ''


############################
## Search
############################
search:
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine: 0

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false


############################
## Marketing
############################
marketing:
  google_analytics: ''
  google_tag_manager: ''
